[tool.poetry]
name = "mongo-client-cache"
version = "0.1.0"
description = ""
authors = ["Alessio Locatelli <software.development@secure.mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pymongo = ">=4.10.1"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-asyncio = "*"
pytest-timeout = "*"
pytest-memray = "*"
python-dotenv = {version = "*", extras = ["cli"]}
tox = "*"
hypothesis = "*"
Faker = "*"
slotscheck = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
