target-version = "py313"

lint.ignore = [
    # Missing copyright notice at top of file
    "CPY001",
    # Missing explicit return at the end of function able to return non-None value
    "RET503",
    # Use of assert detected
    "S101",
    # Standard pseudo-random generators are not suitable for cryptographic purposes
    "S311",
    # Missing author in TODO; try: # TODO(<author_name>): ... or # TODO @<author_name>: ...
    "TD002",
    # Explicitly concatenated string should be implicitly concatenated
    "ISC003",
    # Use `logging.exception` instead of `logging.error`
    "TRY400",
    # missing-trailing-comma
    "COM812",
    # We do not use SQL, so injection is not possible.
    "S608",
    # try/except:pass is a little faster inside functions
    "SIM105",
    # NOTE: Maybe enable this later:
    "D",
    "ERA001",
    "FIX002"
]
lint.select = ["ALL"]

[lint.flake8-builtins]
builtins-ignorelist = ["filter",]

[lint.isort]
combine-as-imports = true


[lint.per-file-ignores]
"tests/**" = ["ARG001", "ARG004", "PLR6301", "FBT001", "PLC2701", "D103"]
