target-version = "py314"

extend-exclude = ["specifications"]

[lint]
select = ["ALL"]
ignore = [
  "D",
  # Trailing comma missing
  "COM812",
  # Use of `assert` detected
  "S101",
  # Magic value used in comparison
  "PLR2004",
  # Too many branches
  "PLR0912",
  # Too many return statements
  "PLR0911",
  # is too complex
  "C901",
  # Too many statements
  "PLR0915",
  # too-many-arguments
  "PLR0913",
  # raw-string-in-exception
  "EM101",
  # Avoid specifying long messages outside the exception class
  "TRY003",
  # print
  "T201",
  # Missing copyright notice at top of file
  "CPY001",
]

[lint.per-file-ignores]
"tests/*" = [
  "SLF001", # Private member accessed.
  "FBT001", # Boolean-typed positional argument in function definition.
]
