target-version = "py314"

extend-exclude = ["specifications"]
force-exclude = true

[lint]
preview = true
select = ["ALL"]
ignore = [
  "D",
  "missing-trailing-comma",
  "assert",
  "magic-value-comparison",
  "too-many-branches",
  "too-many-return-statements",
  "complex-structure",
  "too-many-statements",
  "too-many-arguments",
  "raw-string-in-exception",
  "raise-vanilla-args",
  "print",
  "missing-copyright-notice",
  # Rules from the preview.
  "unnecessary-dunder-call",
  "too-many-locals",
  "noqa-comments",
  "pytest-fixture-autouse",
  "suspicious-subprocess-import",
  "suspicious-non-cryptographic-random-usage",
]

[lint.per-file-ignores]
"tests/*" = [
  "private-member-access",
  "boolean-type-hint-positional-argument",
  "import-private-name",
]
